name: 'Scan -> Whatif -> Deploy'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  pull-requests: write
  
env:
  LOCATION: "westeurope"
  ENVIRONMENT: "production"
  AZURE_RESOURCEGROUP_NAME: "rg-sentinelcicd-dev-001"

jobs:
  # defender-for-devops:
  #   name: 'Defender for DevOps'
  #   # MSDO runs on windows-latest and ubuntu-latest.
  #   # macos-latest supporting coming soon
  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: actions/setup-dotnet@v3
  #     with:
  #       dotnet-version: |
  #         5.0.x
  #         6.0.x
  #   # Run analyzers
  #   - name: Run Microsoft Security DevOps Analysis
  #     uses: microsoft/security-devops-action@preview
  #     id: msdo
  #     with:
  #         categories: 'IaC'
  #   # ***This step doesn't work at the moment:
  #   # Upload alerts to the Security tab
  #   # - name: Upload alerts to Security tab
  #   #   uses: github/codeql-action/upload-sarif@v2
  #   #   with:
  #   #     sarif_file: ${{ steps.msdo.outputs.sarifFile }}

  # bicep-whatif:
  #   name: 'Bicep Whatif'
  #   runs-on: ubuntu-latest
  #   needs: [defender-for-devops]
  #   # environment: production

  #   steps:
  #   # Checkout the repository to the GitHub Actions runner
  #   - name: Checkout
  #     uses: actions/checkout@v3

  #   # Authenticate to Az CLI using OIDC
  #   - name: 'Az CLI login'
  #     uses: azure/login@v1.4.6
  #     with:
  #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
  #    # Checks that all Bicep configuration files adhere to a canonical format
  #   - name: Bicep Lint
  #     uses: Azure/cli@v1
  #     with:
  #       inlineScript: az bicep build --file main.bicep
        
  #   # Validate whether a template is valid at subscription scope
  #   - name: Bicep Validate
  #     uses: Azure/cli@v1
  #     with:
  #       inlineScript: |
  #         az deployment sub validate \
  #           --name validate-${{ github.run_id }} \
  #           --template-file main.bicep \
  #           --parameters @parameters-main.json \
  #           --location $LOCATION     

  #   # Preview changes
  #   - name: "What-If"
  #     uses: Azure/cli@v1
  #     with:
  #       inlineScript: |
  #         az deployment sub what-if \
  #           --name whatif-${{ github.run_id }} \
  #           --template-file main.bicep \
  #           --parameters @parameters-main.json \
  #           --location $LOCATION > whatif
            
  #     # Create string output of Whatif
  #   - name: Create String Output
  #     id: whatif-string
  #     run: |
  #       WHATIF=$(cat whatif)
        
  #       delimiter="$(openssl rand -hex 8)"
  #       echo "summary<<${delimiter}" >> $GITHUB_OUTPUT
  #       echo "## Whatif Output" >> $GITHUB_OUTPUT
  #       echo "<details><summary>Click to expand</summary>" >> $GITHUB_OUTPUT
  #       echo "" >> $GITHUB_OUTPUT
  #       echo '```' >> $GITHUB_OUTPUT
  #       echo "$WHATIF" >> $GITHUB_OUTPUT
  #       echo '```' >> $GITHUB_OUTPUT
  #       echo "</details>" >> $GITHUB_OUTPUT
  #       echo "${delimiter}" >> $GITHUB_OUTPUT

  #   # Publish Terraform Plan as task summary
  #   - name: Publish Whatif to Task Summary
  #     env:
  #       SUMMARY: ${{ steps.whatif-string.outputs.summary }}
  #     run: |
  #       echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY
      
  #   # If this is a PR post the changes
  #   - name: Push Whatif Output to PR
  #     if: github.ref != 'refs/heads/main'
  #     uses: actions/github-script@v6
  #     env:
  #       SUMMARY: "${{ steps.whatif-string.outputs.summary }}"
  #     with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         script: |
  #           const body = `${process.env.SUMMARY}`;
  #           github.rest.issues.createComment({
  #               issue_number: context.issue.number,
  #               owner: context.repo.owner,
  #               repo: context.repo.repo,
  #               body: body
  #           })
  bicep-deploy:
    name: 'Bicep Deploy'
    #TODO can we easily determine if there are any changes to deploy?
    if: github.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest
    # environment: production
    needs: [bicep-whatif]
    
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      with:
        deploymentName: ${{ github.run_number }}
        resourceGroupName: ${{ env.AZURE_RESOURCEGROUP_NAME }}
        template: main.bicep
        parameters: parameters-main.json environmentType=${{ env.ENVIRONMENT }}
            
